# Generated by Django 3.2 on 2021-06-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
