# Generated by Django 3.2 on 2021-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
        ('order_manager', '0002_auto_20210625_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='Cart',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order_manager.Cart', to='product_api.Product'),
        ),
    ]
